version: "3"
services:
  php8cloudtech.net:
    container_name: php8_cloud_tech
    hostname: php8cloudtech.net
    image: php8_cloud_tech
    volumes:
     - ".:/srv/repo"
    ports:
     - "8888:80"
    build: .
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.3.101
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.3.0/24"
